executor: LocalExecutor

postgresql:
  enabled: false

data:
  metadataConnection:
    user: rupeshvn
    pass: gunner
    protocol: postgresql
    host: postgres-postgresql
    port: 5432
    db: stocksdb

config:
  api:
    auth_backends: airflow.api.auth.backend.basic_auth

apiServer:
  service:
    type: NodePort

scheduler:
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"

workers:
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"

triggerer:
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"

images:
  airflow:
    extraPipPackages:
      - yfinance
      - pandas
      - psycopg2-binary

dags:
  gitSync:
    enabled: true
    repo: https://github.com/rupeshvn/stockmarket.git
    branch: main
    subPath: dags