apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: rupeshvn/fastapi-airflow:latest
          imagePullPolicy: Always   # 🔥 IMPORTANT
          ports:
            - containerPort: 8000

          envFrom:
            - secretRef:
                name: fastapi-secret